server.port=8091
spring.application.name=account-service

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

spring.datasource.url=jdbc:postgresql://account-db:5432/account_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.project.account=INFO
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG

# --------------------
# CIRCUIT BREAKER
# --------------------
resilience4j.circuitbreaker.instances.loanService.register-health-indicator=true
resilience4j.circuitbreaker.instances.loanService.sliding-window-size=5
resilience4j.circuitbreaker.instances.loanService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.loanService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.loanService.permitted-number-of-calls-in-half-open-state=3

# --------------------
# RETRY
# --------------------
resilience4j.retry.instances.loanRetry.max-attempts=3
resilience4j.retry.instances.loanRetry.wait-duration=2s

# --------------------
# RATE LIMITER
# --------------------
resilience4j.ratelimiter.instances.loanRateLimiter.limit-for-period=2
resilience4j.ratelimiter.instances.loanRateLimiter.limit-refresh-period=10s
resilience4j.ratelimiter.instances.loanRateLimiter.timeout-duration=0
